sudo: false

language: python

python:
    - "2.7"
    - "pypy3"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install 3to2; fi
    - python setup.py --quiet install

script:
    # Prevent Python 2.7 from using the non-3to2 converted code.
    - rm -rf language-check

    - python test.py

    - python run_doctest.py -v README.rst download_lt.py

    - bash test.bash

    # Smoke test.
    - echo 'This is a sentence.' > foo.txt
    - language-check foo.txt
    - language-check --version
