sudo: false

language: python

python:
    - "2.7"
    - "pypy3"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install 3to2; fi
    - python setup.py --quiet install

script:
    # Prevent Python 2.7 from using the non-3to2 converted code.
    - export PYTHONPATH=""

    - python /home/travis/build/jayvdb/language-check/test.py

    - python /home/travis/build/jayvdb/language-check/run_doctest.py -v /home/travis/build/jayvdb/language-check/README.rst /home/travis/build/jayvdb/language-check/download_lt.py

    - bash /home/travis/build/jayvdb/language-check/test.bash

    # Smoke test.
    - echo 'This is a sentence.' > foo.txt
    - language-check foo.txt
    - language-check --version
